export const entityTypeFields = {
		Person: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			occupation: 'Input',
			birth_date: 'DateInput',
			spans: 'SpansInput',
		},
		Emotion: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			spans: 'SpansInput',
		},
		Feeling: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			timestamp: 'DateTimeInput',
			intensity: 'SliderInput',
			duration: 'DurationInput',
			person_uuid: 'Input',
			concept_uuid: 'Input',
			spans: 'SpansInput',
		},
		Event: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			category: 'Input',
			date: 'DateTimeInput',
			duration: 'DurationInput',
			location: 'Input',
			spans: 'SpansInput',
		},
		Project: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			status: 'Input',
			start_date: 'DateTimeInput',
			target_completion: 'DateTimeInput',
			progress: 'SliderInput',
			spans: 'SpansInput',
		},
		Concept: {
			name: 'Input',
			title: 'Input',
			concept: 'TextAreaInput',
			analysis: 'TextAreaInput',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			source: 'Input',
			spans: 'SpansInput',
		},
		Content: {
			name: 'Input',
			type: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			title: 'Input',
			category: 'Input',
			url: 'Input',
			quotes: 'TextAreaInput',
			status: 'Input',
			author: 'Input',
		},
		Consumable: {
			name: 'Input',
			type: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			category: 'Input',
		},
		Place: {
			name: 'Input',
			type: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			address: 'Input',
			category: 'Input',
		},
		relationship: {
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			spans: 'SpansInput',
		},
};



    