export const entityTypeFields = {
		Person: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			occupation: 'Input',
			birth_date: 'DateInput',
			spans: 'SpansInput',
		},
		Emotion: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			spans: 'SpansInput',
		},
		Feeling: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			timestamp: 'DateTimeInput',
			intensity: 'SliderInput',
			duration: 'DurationInput',
			spans: 'SpansInput',
		},
		Event: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			category: 'Input',
			date: 'Input',
			duration: 'Input',
			location: 'Input',
			spans: 'SpansInput',
		},
		Project: {
			name: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			status: 'Input',
			start_date: 'Input',
			target_completion: 'Input',
			progress: 'Input',
		},
		Concept: {
			name: 'Input',
			type: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			title: 'Input',
			analysis: 'Input',
		},
		Content: {
			name: 'Input',
			type: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			title: 'Input',
			category: 'Input',
			url: 'Input',
			quotes: 'Input',
			status: 'Input',
			author: 'Input',
		},
		Consumable: {
			name: 'Input',
			type: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			category: 'Input',
		},
		Place: {
			name: 'Input',
			type: 'Input',
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			uuid: 'Input',
			address: 'Input',
			category: 'Input',
		},
		relationship: {
			summary_short: 'TextAreaInput',
			summary: 'TextAreaInput',
			spans: 'SpansInput',
		},
};



    